# Generated by Django 5.0.7 on 2024-07-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "phone_no",
                    models.IntegerField(unique=True, verbose_name="Phone Number"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "joined_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="joined data"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
