# Generated by Django 5.0.7 on 2024-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="account",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
